### PR TITLE
WL-3444

### PR DESCRIPTION
**Pull request by nicholaswilson100**

### CODE REVIEW

**Comment by nicholaswilson100** [comment]
Also adding sql for general Contact Us tool.

**Comment by ghost** [comment]
I don't think this belongs in the configuration service, if it is only used by the portal then I'd keep the code locally there.

**Comment by ghost** [comment]
SQL looks good though

**Comment by nicholaswilson100** [comment]
How about in org.sakaiproject.portal.util.ToolUtils.java?

**Comment by ghost** [comment]
I was thinking it looks like a good kind of method to go in the helper.

**Pull request merged**
