### PR TITLE
WL-3444 : making Contact Us site non-joinable, published, and single layout

### PR DESCRIPTION
**Pull request by nicholaswilson100**
Adding newline at file end

### CODE REVIEW

**Comment by nicholaswilson100** [comment]
This relates to WL-3444 in master, portal, kernel , feedback

**Comment by buckett** [comment]
This should really be in the contact us tool, so that the tool is self contained.
You should be able to install a contrib tool without having to patch the kernel.

**Comment by nicholaswilson100** [comment]
ok I'll put it in the contact us tool as a new sql file

**Comment by buckett** [comment]
SQL is now in the tool.

**Pull request closed without merging**
