### PR TITLE
WL-3119 Calendar invites render inline

### PR DESCRIPTION
**Pull request by ghost**
To coerce email client to behave better, we make some adjustments to the
headers. Namely we use:
1. `multipart/alternative` instead of `multipart/mixed` in the top headers
   - this indicates that ical is an alternative rendering of the main email
2. Removes the `Content-Disposition` header
   - this is normally set to `attachment`, which is incorrect
3. Sets the `Content-Type` to `text/calendar`
   - because normally Java doesn't know what the mime type for ics is
4. Adds `method=request` to the `Content-Type`
   - the ical method in question is `REQUEST` so let's make this clear

### CODE REVIEW

**Comment by buckett** [comment]
I'm not sure we should be changing the kernel to force all ical attachments sent out to always change the multipart setup.
Could we add the ContentHeader field to the Attachment and a subtype to the EmailMessage?

**Comment by ghost** [comment]
I'm debating whether it would be better to endow `Attachment` with a `MimeBodyPart` instead, this way we will have more control over the headers externally. Just perhaps too much control.

**Comment by ghost** [comment]
Some additional changes, see commit messages.

**Comment by buckett** [comment]
Should be a good un-breaking change to the kernel.

**Pull request merged**
